openapi: 3.1.0
x-stoplight:
  id: zbwhteau3ge4w
info:
  title: Delivery Bot Retail API
  version: "2.0"
  description: Welcome to Delivery Bot API!<br /><br />This platform allows users to intergration your aplication and website with Delivery Bot's courier network. Wether you need your orders delivered ASAP and through a customer selected time-frame you can now easily automate the process of placing your orders.<br /><br />This developer tool provides you with the necasary documentation, examples, and resources to assist you in creating, managing, and monitoring deliveries.<br /><br />[Postman](https://www.postman.com/deliverybot/workspace/deliver-bot-retail-api/overview)<br />[Github Examples](http://commonmark.org/help/)
  contact:
    email: webmaster@dbx.delivery
    name: Delivery Bot FAQ
    url: "https://dbx.delivery/#contact_us"
  termsOfService: "http://dbx.delivery/terms"
servers:
  - url: "https://api.dbx.delivery"
    description: Production
tags:
  - name: orders
    description: Manage your orders
  - name: slots
    description: Retrieve available time slots
  - name: webhooks
    description: All webhooks are sent to a single url and defined by event property
paths:
  /quote:
    parameters: []
    post:
      tags:
        - orders
      summary: Create a quote
      operationId: post-quote
      responses:
        "200":
          description: Returns quote for delivery
          content:
            application/json:
              schema:
                type: object
                properties:
                  price:
                    type: integer
                x-examples:
                  Example 1:
                    price: 1099
              examples:
                "":
                  $ref: "#/components/examples/timeframe-order"
        "403":
          $ref: "#/components/responses/Autherizarion-Failed"
        "422":
          $ref: "#/components/responses/Invalid-Parameters"
      x-stoplight:
        id: cygorwi9b71ob
      description: "Validates if the order (delivery time, pick up address, delivery address, etc) is servicable by Delivery Bot and return a quote. Quoted price will not change and will be the same regardless of when you place the order."
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Quote"
            examples:
              Simple ASAP quote:
                $ref: "#/components/examples/asap-quote"
              Quote with time-frame:
                $ref: "#/components/examples/timeframe-quote"
  /order:
    post:
      tags:
        - orders
      summary: Create an order
      operationId: post-order
      responses:
        "200":
          description: OK
        "403":
          $ref: "#/components/responses/Autherizarion-Failed"
        "422":
          $ref: "#/components/responses/Invalid-Parameters"
      x-stoplight:
        id: 51klmz4lzce8c
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
            examples:
              Simple ASAP order:
                $ref: "#/components/examples/asap-order"
      description: Creates a new delivery between two addresses.
  "/order/{order_id}":
    get:
      tags:
        - orders
      summary: Get an order
      responses:
        "200":
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
              examples:
                "":
                  $ref: "#/components/examples/timeframe-order"
        "403":
          $ref: "#/components/responses/Autherizarion-Failed"
        "404":
          $ref: "#/components/responses/Not-Found"
      operationId: get-order
      x-stoplight:
        id: hzvs71uuvgwsr
      description: "Get existing order details and status, specified by the order_id in the URL."
    parameters:
      - schema:
          type: string
        name: order_id
        in: path
        required: true
        description: order id of the delivery
    patch:
      tags:
        - orders
      summary: Modify an Order
      operationId: patch-order-order_id
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Order"
              examples:
                "":
                  $ref: "#/components/examples/timeframe-order"
        "403":
          $ref: "#/components/responses/Autherizarion-Failed"
        "404":
          $ref: "#/components/responses/Not-Found"
      x-stoplight:
        id: xjtglb2b0za5c
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Order"
            examples:
              Modify timeframe:
                value:
                  timeframe:
                    service: 2_hour
                    start_time: "2019-08-24T14:15:22Z"
                    end_time: "2019-08-24T14:15:22Z"
              Modify delivery location:
                value:
                  delivery:
                    name: string
                    phone: string
                    note: string
                    location:
                      access_code: string
                      street_address_1: string
                      street_address_2: string
                      city: string
                      zip: string
                      state: string
      description: "Modify an existing delivery, specified by the order_id in the URL. Please refrence our guide regarding allowed updates based on order status."
    put:
      tags:
        - orders
      summary: Cancel an Order
      operationId: put-order-order_id
      responses:
        "200":
          description: OK
        "403":
          $ref: "#/components/responses/Autherizarion-Failed"
        "404":
          $ref: "#/components/responses/Not-Found"
      x-stoplight:
        id: xfd9xdbqimkh7
      description: "Cancel an ongoing or previously placed order, specified by the order_id in the URL."
  /slots:
    parameters: []
    post:
      tags:
        - slots
      summary: Get time slots
      operationId: post-slots
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties: {}
              examples:
                "":
                  value:
                    available_slots:
                      - start_time: "2022-01-18T17:00:00.000+02:00"
                        end_time: "2022-01-18T18:00:00.000+02:00"
                        type: 1_hour
                      - start_time: "2022-01-18T17:00:00.000+02:00"
                        end_time: "2022-01-18T19:00:00.000+02:00"
                        type: 2_hour
      x-stoplight:
        id: hghucg6tnnq84
      description: Returns time slots available between two addresses and specified restrictions.
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Quote"
            examples:
              ASAP slots for today:
                value:
                  restrictions: {}
                  items:
                    - quantity: 3
                      type: 1-hander
                    - quantity: 1
                      type: box
                  pickup:
                    location:
                      street: 400 East 74 Street
                      apt: "301"
                      city: New York
                      zip: "10012"
                      state: NY
                  delivery:
                    location:
                      street: 400 East 74 Street
                      apt: "301"
                      city: New York
                      zip: "10012"
                      state: NY
              Restricted type and dates:
                value:
                  restrictions:
                    1_hour: false
                    2_hour: false
                    same_day: true
                    start_time: "2022-01-18T21:00:00.000+02:00"
                    end_time: "2022-01-18T21:00:00.000+02:00"
                  items:
                    - quantity: 3
                      type: 1-hander
                    - quantity: 1
                      type: box
                  pickup:
                    location:
                      street: 400 East 74 Street
                      apt: "301"
                      city: New York
                      zip: "10012"
                      state: NY
                  delivery:
                    location:
                      street: 400 East 74 Street
                      apt: "301"
                      city: New York
                      zip: "10012"
                      state: NY
  order_assigned:
    parameters: []
    post:
      tags:
        - webhooks
      summary: Order assigned
      operationId: postorder_assigned
      responses:
        "200":
          description: OK
      x-stoplight:
        id: 20o9hi5mxgsy5
  courier_at_pickup:
    post:
      tags:
        - webhooks
      summary: Courier at pickup location
      operationId: post-courier_at_pickup
      responses:
        "200":
          description: OK
      x-stoplight:
        id: xocda2zhvmfd0
    parameters: []
  order_picked_up:
    post:
      tags:
        - webhooks
      summary: Order picked-up
      operationId: post-order_picked_up
      responses:
        "200":
          description: OK
      x-stoplight:
        id: m0p2mh22eqv5v
    parameters: []
  courier_at_delivery:
    parameters: []
    post:
      tags:
        - webhooks
      summary: Courier at delivery location
      operationId: postcourier_at_delivery
      responses:
        "200":
          description: OK
      x-stoplight:
        id: nw7kyy87tx1yr
  order_delivered:
    parameters: []
    post:
      tags:
        - webhooks
      summary: Order delivered
      operationId: postorder_delivered
      responses:
        "200":
          description: OK
      x-stoplight:
        id: 2qctu2kaxwvo9
  order_cancelled:
    parameters: []
    post:
      tags:
        - webhooks
      summary: Order cancelled
      operationId: postorder_cancelled
      responses:
        "200":
          description: OK
      x-stoplight:
        id: l4qmhparo81cg
components:
  schemas:
    Quote:
      type: object
      x-stoplight:
        id: 5akiyb98eijz3
      x-examples:
        Example 1:
          timeframe:
            by: user
            service: 2_hour
            start_time: "2023-11-22T22:00:00Z"
            end_time: "2023-11-22T22:00:00Z"
          items:
            - quantity: 3
              type: 1-hander
            - quantity: 1
              type: box
          pickup:
            location:
              street: 400 East 74 Street
              apt: "301"
              city: New York
              zip: "10012"
              state: NY
              lat: 400.735073
              lon: -73.994431
          delivery:
            location:
              street: 400 East 74 Street
              apt: "301"
              city: New York
              zip: "10012"
              state: NY
              lat: 40.735073
              lon: -73.994431
      properties:
        timeframe:
          $ref: "#/components/schemas/Timeframe"
        items:
          $ref: "#/components/schemas/Items"
        pickup:
          type: object
          properties:
            location:
              $ref: "#/components/schemas/Location"
              x-stoplight:
                id: 9xvl4k6ylmdlp
        delivery:
          type: object
          properties:
            location:
              $ref: "#/components/schemas/Location"
              x-stoplight:
                id: b6qmyv1j84ije
    Order:
      type: object
      x-examples:
        Example 1:
          external_order_id: diu2hi2
          tip: "3.99"
          timeframe:
            service: timeframe
            request: pickup
            start_time: "2023-06-25T15:00:00.000Z"
            end_time: "2023-06-26T00:00:00.000Z"
          items:
            - quantity: 2
              type: box
          products:
            - id: 2
              name: box
              description: box
          pickup:
            name: John Sloko
            phone: (917) 573-7687
            note: This is pickup note
            location:
              access_code: "*3948#"
              street_address_1: 400 East 74th Street
              street_address_2: "301"
              city: NY
              zip: "10012"
              state: NY
            required_verification:
              barocde:
                value: hFu9a0dE
                type: QR
              picture: true
          delivery:
            name: John Sloko
            phone: (917) 573-7687
            note: This is a delivery note
            location:
              access_code: "*3948#"
              street_address_1: 400 East 74th Street
              street_address_2: "301"
              city: NY
              zip: "10012"
              state: NY
            required_verification:
              barocde:
                value: hFu9a0dE
                type: QR
              picture: true
              recipient: false
              signature: false
              pin: true
              identification:
                min_age: 21
      properties:
        external_order_id:
          type: string
        tip:
          type: string
        timeframe:
          $ref: "#/components/schemas/Timeframe"
        items:
          $ref: "#/components/schemas/Items"
        products:
          $ref: "#/components/schemas/Products"
        pickup:
          type: object
          properties:
            name:
              type: string
            phone:
              type: string
            note:
              type: string
            location:
              $ref: "#/components/schemas/Location"
            required_verification:
              type: object
              properties:
                barocde:
                  type: object
                  properties:
                    value:
                      type: string
                    type:
                      type: string
                picture:
                  type: boolean
        delivery:
          type: object
          properties:
            name:
              type: string
            phone:
              type: string
            note:
              type: string
            location:
              $ref: "#/components/schemas/Location"
            required_verification:
              type: object
              properties:
                barocde:
                  type: object
                  properties:
                    value:
                      type: string
                    type:
                      type: string
                picture:
                  type: boolean
                recipient:
                  type: boolean
                signature:
                  type: boolean
                pin:
                  type: boolean
                identification:
                  type: object
                  properties:
                    min_age:
                      type: integer
    Timeframe:
      type: object
      x-examples:
        Example 1:
          by: user
          service: 2_hour
          start_time: "2023-11-22T22:00:00Z"
          end_time: "2023-11-22T22:00:00Z"
      properties:
        by:
          enum:
            - user
            - pickup
            - delivery
        service:
          enum:
            - 2_hour
            - same_day
        start_time:
          type: string
          format: date-time
        end_time:
          type: string
          format: date-time
    Items:
      type: array
      x-examples:
        Example 1:
          items:
            - quantity: 3
              type: 1-hander
            - quantity: 1
              type: box
      items:
        x-stoplight:
          id: rnog775m8v7ef
        type: object
        properties:
          quantity:
            type: integer
            x-stoplight:
              id: h3m3o9j901eff
          type:
            type: string
            x-stoplight:
              id: 1fhl20x5y5dj3
    Products:
      type: array
      x-stoplight:
        id: zbfsnewt7gsk0
      x-examples:
        Example 1:
          items:
            - quantity: 3
              type: 1-hander
            - quantity: 1
              type: box
      items:
        type: object
        properties:
          id:
            type: integer
            x-stoplight:
              id: o7d65ha1fdog8
          name:
            type: string
            x-stoplight:
              id: 8i2rqvakldck3
          description:
            type: string
            x-stoplight:
              id: sui0wkx1cgltz
    Location:
      type: object
      properties:
        access_code:
          type: string
        street_address_1:
          type: string
        street_address_2:
          type: string
        city:
          type: string
        zip:
          type: string
        state:
          type: string
      x-examples:
        Example 1:
          access_code: "*3948#"
          street_address_1: 400 East 74th Street
          street_address_2: "301"
          city: NY
          zip: "10012"
          state: NY
  securitySchemes:
    API Key:
      name: apiKey
      type: apiKey
      in: query
  requestBodies: {}
  examples:
    asap-quote:
      value:
        items:
          - quantity: 3
            type: 1-hander
          - quantity: 1
            type: box
        pickup:
          location:
            street: 400 East 74 Street
            apt: "301"
            city: New York
            zip: "10012"
            state: NY
        delivery:
          location:
            street: 400 East 74 Street
            apt: "301"
            city: New York
            zip: "10012"
            state: NY
    timeframe-quote:
      value:
        timeframe:
          service: 2_hour
          start_time: "2023-11-22T22:10:00Z"
          end_time: "2023-11-22T22:12:00Z"
        items:
          - quantity: 3
            type: 1-hander
          - quantity: 1
            type: box
        pickup:
          location:
            street: 400 East 74 Street
            apt: "301"
            city: New York
            zip: "10012"
            state: NY
        delivery:
          location:
            street: 400 East 74 Street
            apt: "301"
            city: New York
            zip: "10012"
            state: NY
    asap-order:
      value:
        external_order_id: diu2hi2
        tip: "3.99"
        items:
          - quantity: 2
            type: box
        products:
          - id: 2
            name: box
            description: box
        pickup:
          name: John Sloko
          phone: (917) 573-7687
          note: This is pickup note
          location:
            access_code: "*3948#"
            street_address_1: 400 East 74th Street
            street_address_2: "301"
            city: NY
            zip: "10012"
            state: NY
          required_verification:
            barocde:
              value: hFu9a0dE
              type: QR
            picture: true
        delivery:
          name: John Sloko
          phone: (917) 573-7687
          note: This is a delivery note
          location:
            access_code: "*3948#"
            street_address_1: 400 East 74th Street
            street_address_2: "301"
            city: NY
            zip: "10012"
            state: NY
          required_verification:
            barocde:
              value: hFu9a0dE
              type: QR
            picture: true
            recipient: false
            signature: false
            pin: true
            identification:
              min_age: 21
    timeframe-order:
      value:
        external_order_id: diu2hi2
        tip: "3.99"
        timeframe:
          service: 2_hour
          start_time: "2023-06-25T15:00:00.000Z"
          end_time: "2023-06-26T00:00:00.000Z"
        items:
          - quantity: 2
            type: box
        products:
          - id: 2
            name: box
            description: box
        pickup:
          name: John Sloko
          phone: (917) 573-7687
          note: This is pickup note
          location:
            access_code: "*3948#"
            street_address_1: 400 East 74th Street
            street_address_2: "301"
            city: NY
            zip: "10012"
            state: NY
          required_verification:
            barocde:
              value: hFu9a0dE
              type: QR
            picture: true
        delivery:
          name: John Sloko
          phone: (917) 573-7687
          note: This is a delivery note
          location:
            access_code: "*3948#"
            street_address_1: 400 East 74th Street
            street_address_2: "301"
            city: NY
            zip: "10012"
            state: NY
          required_verification:
            barocde:
              value: hFu9a0dE
              type: QR
            picture: true
            recipient: false
            signature: false
            pin: true
            identification:
              min_age: 21
  responses:
    Not-Found:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
              error:
                type: string
              messege:
                type: string
            x-examples:
              Example 1:
                code: invalid_delivery_parameters
                error: outside_of_delivery_time.
                messege: Ready by time outside of delivery hours.
          examples:
            "":
              value:
                code: not_found
                error: order_not_found
                message: "Order_id: 0 not found"
    Invalid-Parameters:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            x-examples:
              Example 1:
                code: invalid_params
                message: One or more fields couldn't be validated.
                field_error:
                  - field: deliver_to
                    error: Invalid deliver to value.
                  - field: name
                    error: Minimum character length for  name is 2.
                  - field: phone
                    error: "Invalid phone number format. Required format: “+xxxxxxxxxx“."
                  - field: item2
                    error: "Invalid item value. Allowed items: “box”, “heavy-box”, “large-box”, “1-hander”, “2-hander”, “plant”, “bag”, “letter”, “garment”, “other”."
            properties:
              code:
                type: string
              message:
                type: string
              field_error:
                type: array
                items:
                  type: object
                  properties:
                    field:
                      type: string
                    error:
                      type: string
          examples:
            "":
              value:
                code: invalid_params
                message: One or more fields couldn't be validated.
                field_error:
                  - field: name
                    error: Minimum character length for  name is 2.
                  - field: phone
                    error: "Invalid phone number format. Required format: “+xxxxxxxxxx“."
    Unprocessable-Entity:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
              error:
                type: string
              messege:
                type: string
            x-examples:
              Example 1:
                code: invalid_delivery_parameters
                error: outside_of_delivery_zone
                messege: Address outside of delivery zone.
          examples:
            Invalid Timeframe:
              value:
                code: invalid_parameters
                error: invalid_timeframe
                title: start_time and end_time must be 2 hours or same-day (2PM-7PM).
            Outside delivery zone:
              value:
                code: invalid_parameters
                error: outside_of_delivery_zone
                messege: Address outside of delivery zone.
    Autherizarion-Failed:
      description: Example response
      content:
        application/json:
          schema:
            type: object
            properties:
              code:
                type: string
              message:
                type: string
            x-examples:
              Example 1:
                code: authorization_failed
                message: Invalid authorization token.
          examples:
            "":
              value:
                code: authorization_failed
                message: Invalid authorization token.
security:
  - API Key: []
